# Generated by Django 3.0.3 on 2020-03-10 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slickpackage', '0002_category_package'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='package',
            new_name='thepackage',
        ),
    ]
