# Generated by Django 3.0.3 on 2020-03-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slickpackage', '0003_auto_20200310_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thepackage',
            old_name='image',
            new_name='image01',
        ),
        migrations.AddField(
            model_name='thepackage',
            name='image02',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='thepackage',
            name='image03',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
