# Generated by Django 3.0.3 on 2020-03-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slickpackage', '0007_thepackage_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='image',
            new_name='image01',
        ),
        migrations.AddField(
            model_name='categories',
            name='image02',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='categories',
            name='image03',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
