# Generated by Django 3.0.3 on 2020-03-20 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slickpackage', '0011_snippet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='sunject',
            new_name='subject',
        ),
    ]
