# Generated by Django 3.0.3 on 2020-03-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slickpackage', '0013_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='special',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
