# Generated by Django 3.0.3 on 2020-03-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slickpackage', '0015_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='description',
        ),
        migrations.AddField(
            model_name='process',
            name='detail',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='process',
            name='step',
            field=models.CharField(max_length=20),
        ),
    ]
