# Generated by Django 3.0.3 on 2020-03-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slickpackage', '0016_auto_20200321_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='detail',
            field=models.TextField(),
        ),
    ]
