# Generated by Django 3.0.3 on 2020-03-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slickpackage', '0017_auto_20200321_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='detail',
            new_name='detail01',
        ),
        migrations.RenameField(
            model_name='process',
            old_name='image',
            new_name='image01',
        ),
        migrations.RenameField(
            model_name='process',
            old_name='step',
            new_name='step01',
        ),
        migrations.AddField(
            model_name='process',
            name='detail02',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process',
            name='detail03',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process',
            name='image02',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='process',
            name='image03',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='process',
            name='step02',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process',
            name='step03',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
