# Generated by Django 3.0.3 on 2020-03-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slickpackage', '0018_auto_20200321_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippetquote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('ContactNumber', models.CharField(max_length=50)),
                ('PackageType', models.CharField(max_length=50)),
                ('Dimensions', models.CharField(max_length=50)),
                ('Quantity', models.CharField(max_length=50)),
                ('Specification', models.TextField()),
            ],
        ),
    ]
