# Generated by Django 3.0.3 on 2020-03-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slickpackage', '0019_snippetquote'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryproduct',
            name='DefaultProcess',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industryproduct',
            name='Dimensions',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industryproduct',
            name='Finishing',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industryproduct',
            name='Options',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industryproduct',
            name='OrderQuantity',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industryproduct',
            name='PaperStock',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industryproduct',
            name='Printing',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industryproduct',
            name='Proof',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
