# Generated by Django 3.0.3 on 2020-03-22 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slickpackage', '0020_auto_20200322_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='packagesub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image01', models.ImageField(blank=True, null=True, upload_to='')),
                ('image02', models.ImageField(blank=True, null=True, upload_to='')),
                ('image03', models.ImageField(blank=True, null=True, upload_to='')),
                ('OrderQuantity', models.CharField(max_length=32)),
                ('Dimensions', models.CharField(max_length=32)),
                ('Printing', models.CharField(max_length=32)),
                ('PaperStock', models.CharField(max_length=32)),
                ('Finishing', models.CharField(max_length=32)),
                ('Options', models.CharField(max_length=32)),
                ('DefaultProcess', models.CharField(max_length=32)),
                ('Proof', models.CharField(max_length=32)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slickpackage.thepackage')),
            ],
        ),
    ]
